### ISSUE TITLE
Is trying to access ~/.config/gitconfigs but in macos system the path is ~/.gitconfig

### ISSUE THREAD

**Issue by airtonGit** [TheYkk/git-switcher#8]
Hi,

Is trying to access 
`~/.config/gitconfigs` and is panicing.

But in my macos system the right path is 
`~/.gitconfig`
There is a way to configure it?

thank you

**Comment by TheYkk** [comment]
Hi ,

The git switcher uses `~/.config/gitconfigs` path to store multiple git profiles.
